version: '3.8'

services:
  zitadel:
    restart: 'always'
    networks:
      - 'zitadel'
    image: 'ghcr.io/zitadel/zitadel:latest'
    command: 'start-from-init --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode disabled'
    environment:
      - 'ZITADEL_DATABASE_COCKROACH_HOST=crdb'
      - 'ZITADEL_EXTERNALSECURE=false'
      - ZITADEL_DEFAULTINSTANCE_CUSTOMDOMAIN=localhost
      - ZITADEL_DEFAULTINSTANCE_DOMAINPOLICY_SMTPSENDERADDRESSMATCHESINSTANCEDOMAIN=false
      - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_HOST=smtp.gmail.com:587
      - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_TLS=true
      - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_FROM=zitadel-admin@zitadel.localhost
      - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_FROMNAME=ZITADEL Admin
    depends_on:
      crdb:
        condition: 'service_healthy'
    ports:
      - '8080:8080'

  crdb:
    restart: 'always'
    networks:
      - 'zitadel'
    image: 'cockroachdb/cockroach:v22.1.3'
    command: 'start-single-node --insecure'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health?ready=1"]
      interval: '10s'
      timeout: '30s'
      retries: 5
      start_period: '20s'
    ports:
      - '9090:8080'
      - '26257:26257'

  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    networks:
      - 'zitadel'
    ports:
      - '5000:80'
      - '25:25'
      - '143:143'
    volumes:
        - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__HostName=smtp4dev
      - ServerOptions__TlsMode=StartTls


networks:
  zitadel:

volumes:
  smtp4dev-data: